# Vendored from Autorelease 0.6.1
# Update by updating Autorelease and running `autorelease vendor actions`
name: "Autorelease Release"
on:
  push:
    branches:
      # TODO: this should come from yaml conf
      - stable

jobs:
  release-gh:
    if: ${{ github.repository == 'openpathsampling/openpathsampling' }}
    runs-on: ubuntu-latest
    name: "Cut release"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |  # TODO: move this to an action
          source ./.github/workflows/autorelease-default-env.sh
          if [ -f "autorelease-env.sh" ]; then
            cat autorelease-env.sh >> $GITHUB_ENV
          fi
          if [ -f "./.autorelease/install-autorelease" ]; then
            source ./.autorelease/install-autorelease
          else
            eval $INSTALL_AUTORELEASE
          fi
        name: "Install autorelease"
      - run: |
          VERSION=`python setup.py --version`
          PROJECT=`python setup.py --name`
          echo $PROJECT $VERSION
          autorelease-release --project $PROJECT --version $VERSION --token $AUTORELEASE_TOKEN
        env:
          AUTORELEASE_TOKEN: ${{ secrets.AUTORELEASE_TOKEN }}
        name: "Cut release"
