# Workflow to test against release candidate of OpenMM.
# See also: check-openmm-rc.yml
name: "Test OpenMM Release Candidate"
on:
  workflow_dispatch:
  workflow_call:
  # use this for debugging
  #pull_request:
    #branch: master

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Tests"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with: 
          auto-update-conda: true
      - name: "Install requirements"
        run: |
          # we'd rather use the default Python version, but for now need to
          # pin to 3.9 (see openpathsampling/openpathsampling#1093)
          #CONDA_PY=$(python -c "import sys; print('.'.join(str(s) for s in sys.version_info[:2]))")
          export CONDA_PY=3.9
          echo "Python version: ${CONDA_PY}"
          source devtools/conda_install_reqs.sh
      - name: "Install OpenMM RC"
        run: |
          conda install -c conda-forge/label/openmm_rc -c conda-forge openmm
      - name: "Install"
        run: |
          python -m pip install --no-deps -e .
          python -c "import openpathsampling"
      - name: "Versions"
        run: conda list
      - name: "Unit Tests"
        env:
          PY_COLORS: "1"
        run: py.test -vv -s --cov --cov-report xml
      - name: "Tests: Experimental"
        if: matrix.MINIMAL == '' && matrix.CONDA_PY != '2.7'
        run: py.test openpathsampling/experimental/ -vv -s
      - name: "Notebook tests"
        run: |
          pushd examples/ && ./ipynbtests.sh || exit 1 && popd
